### PR TITLE
keep alternate

### PR DESCRIPTION
**Pull request by zavr-1**
https://github.com/google/closure-stylesheets requires `/* @alternate */` syntax for same-property declarations. I understand that your motivation behind clearing comments is so to avoid matching rules that are actually commented out, but that wouldn't be an issue with `@alternate`. is it OK? Otherwise I can't compile bootstrap with closure after running it with DropCSS. ta

### CODE REVIEW

**Comment by leeoniya** [comment]
hey @zavr-1 

>  I understand that your motivation behind clearing comments is so to avoid matching rules that are actually commented out

the real motivation is to simplify and speed up the parser. since comments can be encountered almost anywhere, the parser has to handle them all over the place, which increases complexity and reduces perf.

cutting out an exception for a single annotation like this, which is required by a specific tool is too narrow. if there's a need to keep comments, then it should be handled generically.

DropCSS should ideally be run post-minification/compilation so that it does not have to handle various annotations like this. this also offloads a lot of parsing quirks and syntax oddities to more robust tools.

while i understand that it may take longer to compile a giant pile of css with another tool first, i don't want to carve out exceptions that imply that DropCSS can be run on source files like SASS,etc. PurgeCSS operates on source files, but produces worse results.

if this solution works for your case, then just keep a lightly modified fork for yourself.

**Comment by zavr-1** [comment]
jeez that's why there are options for the program, if one does not add the flag, it works just as before. you're already having a comments regex, therefore nothing is slowed down. this is just in addition to the fact that it's 2019 and you can run this regex in 1ms on a 1kb CSS.
you've made a tool that works with CSS, so to say that it's a narrow use case to use it with closure is simply false. Even if I'm the only user of closure stylesheets which I'm not I'm still a user. 
next, I can't simply add the comment back because the generator messes up the output like crazy, I'd rather have a neat annotated input CSS which I can maintain alright, instead of having a regex that would update the generated code.
finally, i wanted to use it as a post processor, i.e. i ran it through closure first then dropcss, but i had to run it through closure again to produce a debug version which can be differed, because once again, the output by dropcss is not pretty, but closure can make it pretty plus i needed to rename classes back.

sure I'll maintain my fork just don't know what's the need to alienate your users like this when all it takes is to merge 3 lines omg

**Comment by leeoniya** [comment]
ok, let me be blunt.

first, this PR is a complete hack which invokes *undefined behavior* in DropCSS. there is **zero** handling of comment parsing in this library, both before and after your change. by leaving *any* comments in, you are introducing the possibility of breaking the parser in many unforeseen cases. you have added exactly 0 tests. the fact that it works *at all* in your specific use case is by sheer luck. this is absolutely not how features get added to libraries i maintain.

even if the implementation was done properly, `keepAlternate` is an incredibly processor-specific *and* case-specific addition. it is the difference between saying "comments are stripped" and "comments are stripped unless they're `/* @alternate */` to satisfy the `closure-stylesheets`, and only if you enable this processor-specific flag". that doesn't sound like a ridiculously specific feature to you? what about the hundreds of other pre-processor features that `closure-stylesheets` offers? should there be a hack and flag for each of those as soon as *you* have a need for them? and no, you're not the only one using `closure-stylesheets`, but that's meaningless. millions more use SASS, LESS, PostCSS, etc. and i'm not about to add exceptions even for those.

the only way this feature will happen is if you (or someone) implements *proper*, general comment handling, *with tests*, and shows me that it has minimal impact on perf and code size, and keeps complexity manageable. what you have here is nothing of the sort. i appreciate your feedback, bug reporting and suggestions, but you need to understand that i have the necessary experience and judgement to make the correct decisions for this project. i'm open to being convinced, but you have not done so. venting your frustration after a single review comment will get you absolutely nowhere.

**Comment by zavr-1** [comment]
>  there is zero handling of comment parsing in this library, both before and after your change
well this is false isn't because you strip comments. 
> you didn't add tests
yeah because i knew it wouldn't be merged, if you said "can you add a test" then ok 
> venting frustration 
there's a tendency for people to justify their conservative view of the world consisting of "my software nobody can touch it" by telling that others are venting off at them. i gave you a valid reason why i can't work around this particular issue - because your lib prints output in an unpredictable manner which makes it impossible to place a regex there. don't blame me for everything ok i know people like thinking they are saints and it's others all the time who are venting villains when there's actually a valid use case and concern about functionality, right, there is not a single code branch that would be executed differently without adding `keepAlternate` in the config, did you ask me "can you add a test for this" no you said that "my software i don't want that i don't care about the users i'm the most skilled programmer in the world i know everything myself" plus i don't even install all that 3k dependencies that come with this package to just run mocha because i have respect for myself. 
ok dude farewell i'll make my own dropper with hookers

**Comment by leeoniya** [comment]
> well this is false isn't because you strip comments.

this isn't some debatable point. they are stripped before any further parsing is done specifically so they don't have to be handled in the parser's regexs. you should just take my word for it instead of arguing since i wrote the fucking lib.

> yeah because i knew it wouldn't be merged, if you said "can you add a test" then ok

it's wasn't going to be merged for all the other reasons i already listed. so you're right, a test wouldn't have done anything. in any case, a proper test would have shown you that not stripping out comments will break the parser if they appear anywhere except *exactly* where they fall into the parser's undefined behavior.

> i gave you a valid reason why i can't work around this particular issue - because your lib prints output in an unpredictable manner which makes it impossible to place a regex there.

what exactly is "impossible" about re-inserting `/* @alternate */` in front of consecutively-defined identical properties? i don't fucking owe this to you, but since you seem to lack imagination: https://jsfiddle.net/0b8ucq5p/

> ok dude farewell i'll make my own dropper with black jack and hookers

terrific. go troll some other author of a lib you enjoy using. if you ever manage to shed your unearned sense of entitlement, then feel free to come back. bye!

**Pull request closed without merging**
